Repository hacktoberfest-unicam/awesome-hacktoberfest-cobalt-capybara, pull requests merged in 2024-10, with the labels that each got.

#6 Imp
  Palestra di Dennis Ritchie (IMP)/Level Check/README.md
  Palestra di Dennis Ritchie (IMP)/Level Check/nonSeiBarvo/LevelCheck.py
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/nonSeiBarvo/PokemonBattle.py
  Palestra di Dennis Ritchie (IMP)/Trading System/nonSeiBarvo/TradingSystem.py
Labels: hacktoberfest-accepted

#7 Challenge
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/team24/battle_calculation.py
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/team24/pokemon.py
  Palestra di Edsger Dijkstra (ASD)/Research/team24/search.py
  Palestra di Edsger Dijkstra (ASD)/Sorting/team24/sorting.py
Labels: in-progress

#10 Primo challenge IMP concluso
  Palestra di Dennis Ritchie (IMP)/Level Check/Challenge1.py
Labels: in-progress, complete

#11 Ritche team24
  Palestra di Dennis Ritchie (IMP)/Level Check/team24/solve.py
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/team24/battle.py
  Palestra di Dennis Ritchie (IMP)/Trading System/team24/trading.py
Labels: in-progress

#13 [IMP challeng commit] team 11
  Palestra di Dennis Ritchie (IMP)/Level Check/team11/LevelCheck.py
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/team11/Battle.py
  Palestra di Dennis Ritchie (IMP)/Trading System/Team11/Trading.py
Labels: hacktoberfest-accepted

#17 IMP
  Palestra di Barbara Liskov (OOP)/Centro LEAKS X.jpeg
  Palestra di Dennis Ritchie (IMP)/Level Check/Team2/LevelCheck.py
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team 2/Pokemon_battle.py
  Palestra di Dennis Ritchie (IMP)/Trading System/Team2/traiding.py
Labels: hacktoberfest-accepted, complete

#18 Risolta 1 challenge ASD su sorting, implementati Bubble Sort e Quick Sort
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/Team25/soluzioneBattleDamage.py
  Palestra di Edsger Dijkstra (ASD)/Research/Team25/soluzioneResearch.py
  Palestra di Edsger Dijkstra (ASD)/Sorting/Team25/soluzioneSorting.py
Labels: hacktoberfest-accepted, in-progress

#20 OOP Challenge Team 11 completed
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/Team11/BackpackInventory.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/Team11/BattleArena.py
  Palestra di Barbara Liskov (OOP)/Evolution/Team11/Evolution.py
Labels: hacktoberfest-accepted, complete

#30 [complite] palestra asd
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/Team16/Advantage.java
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/Team16/Main.java
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/Team16/Pokemon.java
  Palestra di Edsger Dijkstra (ASD)/Research/Team16/Main.java
  Palestra di Edsger Dijkstra (ASD)/Research/Team16/Pokemon.java
  Palestra di Edsger Dijkstra (ASD)/Research/Team16/Research.java
  Palestra di Edsger Dijkstra (ASD)/Sorting/Team16/BubbleSort.java
  Palestra di Edsger Dijkstra (ASD)/Sorting/Team16/Main.java
  Palestra di Edsger Dijkstra (ASD)/Sorting/Team16/Pokemon.java
  Palestra di Edsger Dijkstra (ASD)/Sorting/Team16/Sort.java
Labels: hacktoberfest-accepted, complete

#34 22 palestra liskov
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/22-Backpack/Backpack.java
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/22-Backpack/Item.java
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/22-Backpack/Main.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/BattleArena.java
  Palestra di Barbara Liskov (OOP)/Evolution/22-Evolution/Charizard.java
  Palestra di Barbara Liskov (OOP)/Evolution/22-Evolution/Charmander.java
  Palestra di Barbara Liskov (OOP)/Evolution/22-Evolution/Charmeleon.java
  Palestra di Barbara Liskov (OOP)/Evolution/22-Evolution/Main.java
  Palestra di Barbara Liskov (OOP)/Evolution/22-Evolution/Pokemon.java
Labels: hacktoberfest-accepted, in-progress

#36 challenges IMP
  Palestra di Dennis Ritchie (IMP)/Level Check/Team10/SortingCallange.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team10/PokemonBatle.py
  Palestra di Dennis Ritchie (IMP)/Trading System/Team 10/TradingSystem.py
Labels: hacktoberfest-accepted, in-progress

#37 ASD Team11 - complete
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/Team11/PkmnBattleDamageCalc.py
  Palestra di Edsger Dijkstra (ASD)/Research/Team11/Research.py
  Palestra di Edsger Dijkstra (ASD)/Sorting/TEAM11/Sorting.py
Labels: hacktoberfest-accepted, in-progress

#39 Imp
  Palestra di Tim Berners-Lee (WEB DEV)/Pokedex implementation/Team 1/index.html
  Palestra di Tim Berners-Lee (WEB DEV)/Pokedex implementation/Team 1/script.js
  Palestra di Tim Berners-Lee (WEB DEV)/Pokedex implementation/Team 1/styles.css
  Palestra di Tim Berners-Lee (WEB DEV)/Pokemon REST Wrapper/HACKTOBERFEST/app.py
  Palestra di Tim Berners-Lee (WEB DEV)/Sanity Check [EASY]/sito 2 pokemon TEAM1/index.html
  Palestra di Tim Berners-Lee (WEB DEV)/Sanity Check [EASY]/sito 2 pokemon TEAM1/script.js
  Palestra di Tim Berners-Lee (WEB DEV)/Sanity Check [EASY]/sito 2 pokemon TEAM1/styles.css
Labels: hacktoberfest-accepted, complete

#19 aggiunta chall level check IMP
  Palestra di Dennis Ritchie (IMP)/Level Check/team3/LevelCheck.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Battle.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Main.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Pokemon.java
  Palestra di Dennis Ritchie (IMP)/Trading System/Trading.java
Labels: hacktoberfest-accepted, in-progress

#43 [fix]
  Palestra di Tim Berners-Lee (WEB DEV)/Pokedex implementation/Team 1/index.html
  Palestra di Tim Berners-Lee (WEB DEV)/Pokedex implementation/Team 1/script.js
  Palestra di Tim Berners-Lee (WEB DEV)/Pokedex implementation/Team 1/styles.css
  Palestra di Tim Berners-Lee (WEB DEV)/Pokemon REST Wrapper/Team 1/app.py
  Palestra di Tim Berners-Lee (WEB DEV)/Sanity Check [EASY]/sito 2 pokemon TEAM1/index.html
  Palestra di Tim Berners-Lee (WEB DEV)/Sanity Check [EASY]/sito 2 pokemon TEAM1/script.js
  Palestra di Tim Berners-Lee (WEB DEV)/Sanity Check [EASY]/sito 2 pokemon TEAM1/styles.css
Labels: hacktoberfest-accepted, complete

#45 22 dennis ritchie
  Palestra di Dennis Ritchie (IMP)/Level Check/22-LevelCheck/.gitkeep
  Palestra di Dennis Ritchie (IMP)/Level Check/22-LevelCheck/PokemonLevelSorter.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/22-PokemonBattle/Pokemon.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/22-PokemonBattle/PokemonBattle.java
  Palestra di Dennis Ritchie (IMP)/Trading System/22-PokemonTrading/PokemonTrading.java
Labels: hacktoberfest-accepted

#41 26 staff
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/.gitignore
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/build.gradle
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/gradle/wrapper/gradle-wrapper.jar
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/gradle/wrapper/gradle-wrapper.properties
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/gradlew
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/settings.gradle
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/src/main/java/it/alessandrocalista/backpack/Main.java
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/src/main/java/it/alessandrocalista/backpack/container/Backpack.java
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/26-staff/BackpackInventory/src/main/java/it/alessandrocalista/backpack/item/Item.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/Main.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/Move.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/Pokemon.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/PokemonMoveSet.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/PokemonStatistics.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/battle/Battle.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/battle/entity/LivingEntity.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/status/CountingStatus.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/status/ParalyzedStatus.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/status/SleepingStatus.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/status/Status.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/type/ElectricPokemon.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/type/FirePokemon.java
  Palestra di Barbara Liskov (OOP)/Battle Arena/26-staff/BattleArenaComputer/src/main/java/it/alessandrocalista/pokemon/type/WaterPokemon.java
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/.gitignore
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/build.gradle
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/gradle/wrapper/gradle-wrapper.jar
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/gradle/wrapper/gradle-wrapper.properties
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/gradlew
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/settings.gradle
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/src/main/java/it/alessandrocalista/Charizard.java
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/src/main/java/it/alessandrocalista/Charmander.java
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/src/main/java/it/alessandrocalista/Charmeleon.java
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/src/main/java/it/alessandrocalista/Main.java
  Palestra di Barbara Liskov (OOP)/Evolution/26-staff/PokemonEvolution/src/main/java/it/alessandrocalista/Pokemon.java
Labels: hacktoberfest-accepted, complete

#46 Oop
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/NonSeiBarvo/Backpack.py
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/NonSeiBarvo/Item.py
  Palestra di Barbara Liskov (OOP)/Backpack Inventory/NonSeiBarvo/main.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/battle.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/effectiveness_chart.json
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/enums/moves_enum.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/enums/pokemons_enum.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/fire_pokemon.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/main.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/move.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/pokemon.py
  Palestra di Barbara Liskov (OOP)/Battle Arena/NonSeiBarvo/water_pokemon.py
  Palestra di Barbara Liskov (OOP)/Evolution/NonSeiBarvo/pokemon_evolution.py
Labels: hacktoberfest-accepted

#28 Aggiunto link per progetto Figma
  Palestra di Donald Norman (UI-UX)/Pokedex Redraw/pokedex-figmaUIUX.txt
  Palestra di Donald Norman (UI-UX)/Pokemon Personalization/Personalizzazione Pokémon (Bozza)-figmalink.txt
Labels: hacktoberfest-accepted

#51 sofia team 23
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/Team23/BattleCalculations.java
  Palestra di Edsger Dijkstra (ASD)/Pokemon Battle Damage Calculator/Team23/Pokemon.java
  Palestra di Edsger Dijkstra (ASD)/Research/Team23/SearchPokemon.java
  Palestra di Edsger Dijkstra (ASD)/Sorting/Team23/SortPokemon.java
Labels: hacktoberfest-accepted

#49 Palestra di dennis ritchie (imp)
  Palestra di Dennis Ritchie (IMP)/Level Check/Team 9/README.md
  Palestra di Dennis Ritchie (IMP)/Level Check/Team 9/src/App.java
  Palestra di Dennis Ritchie (IMP)/Level Check/Team 9/src/utils/std/README.md
  Palestra di Dennis Ritchie (IMP)/Level Check/Team 9/src/utils/std/StdIn.java
  Palestra di Dennis Ritchie (IMP)/Level Check/Team 9/src/utils/std/StdOut.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team 9/README.md
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team 9/src/App.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team 9/src/Pokemon.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team 9/src/utils/std/README.md
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team 9/src/utils/std/StdIn.java
  Palestra di Dennis Ritchie (IMP)/Pokemon Battle/Team 9/src/utils/std/StdOut.java
Labels: hacktoberfest-accepted

#48 FUN challenge Team11 2/3 challenge completed
  Palestra di Haskell Curry (FUN)/Catch System/TEAM11/CatchSystem.hs
  Palestra di Haskell Curry (FUN)/Pokemon Damage Calculator/Team11/PkmnDamageCalc.hs
  Palestra di Haskell Curry (FUN)/Pokemon Filter/TEAM11/PokemonFilter.hs
Labels: in-progress

#53 Trading sys
  Palestra di Dennis Ritchie (IMP)/Trading System/Team 9/README.md
  Palestra di Dennis Ritchie (IMP)/Trading System/Team 9/src/App.java
  Palestra di Dennis Ritchie (IMP)/Trading System/Team 9/src/utils/std/README.md
  Palestra di Dennis Ritchie (IMP)/Trading System/Team 9/src/utils/std/StdIn.java
  Palestra di Dennis Ritchie (IMP)/Trading System/Team 9/src/utils/std/StdOut.java
Labels: hacktoberfest-accepted, complete

#52 Sort Pokemon Levels
  Palestra di Dennis Ritchie (IMP)/Level Check/26-staff/main.py
Labels: hacktoberfest-accepted, complete
